[package]
name = "staticmap-rs"
version = "0.1.0"
authors = ["danielalvsaaker <daniel@nopemail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
rayon = "1.1"
reqwest = { version = "0.10", features = ["blocking"] }
imageproc = "*"
