[package]
name = "staticmap"
version = "0.1.0"
authors = ["danielalvsaaker <daniel@nopemail.net>"]
edition = "2018"
description = "Static map generator"
repository = "https://github.com/danielalvsaaker/staticmap"
readme = "README.md"
license = "GPL-3.0-only"
categories = ["multimedia::images"]
keywords = ["openstreetmap", "osm", "map"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.23.10", default-features = false, features = ["png"] }
rayon = "1.1"
attohttpc = { version = "0.15", default-features = false, features = ["tls-rustls"] }
raqote = { version = "0.8.0", default-features = false }
